"""add node inbound usage table

Revision ID: 92a883106837
Revises: 7bca3e6f6f4b
Create Date: 2026-08-08 01:37:10.317042

"""
from alembic import op
import sqlalchemy as sa
import app.db.compiles_types


# revision identifiers, used by Alembic.
revision = '92a883106837'
down_revision = '7bca3e6f6f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_inbound_usages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=True),
    sa.Column('inbound_tag', sa.String(length=256), nullable=False),
    sa.Column('uplink', sa.BigInteger(), nullable=False),
    sa.Column('downlink', sa.BigInteger(), nullable=False),
    sa.Column('id', app.db.compiles_types.SqliteCompatibleBigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_inbound_usages_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_inbound_usages')),
    sa.UniqueConstraint('created_at', 'node_id', 'inbound_tag', name=op.f('uq_node_inbound_usages_created_at'))
    )
    with op.batch_alter_table('node_inbound_usages', schema=None) as batch_op:
        batch_op.create_index('ix_node_inbound_usages_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_node_inbound_usages_tag_created_at', ['inbound_tag', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_inbound_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_node_inbound_usages_tag_created_at')
        batch_op.drop_index('ix_node_inbound_usages_created_at')

    op.drop_table('node_inbound_usages')
    # ### end Alembic commands ###
