"""store the allowance each verdict used

Revision ID: 9338a6417365
Revises: f174c3b13642
Create Date: 2026-08-08 22:23:39.351992

"""
from alembic import op
import sqlalchemy as sa

import app.db.compiles_types


# revision identifiers, used by Alembic.
revision = '9338a6417365'
down_revision = 'f174c3b13642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_connection_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_applied', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_connection_states', schema=None) as batch_op:
        batch_op.drop_column('limit_applied')

    # ### end Alembic commands ###
