"""add connection limiter tables

Revision ID: f174c3b13642
Revises: b8c2d5f1a943
Create Date: 2026-08-08 19:17:37.783429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

import app.db.compiles_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f174c3b13642'
down_revision = 'b8c2d5f1a943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_restrictions',
    sa.Column('user_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_count', sa.Integer(), nullable=False),
    sa.Column('ip_limit', sa.Integer(), nullable=False),
    sa.Column('observed_ips', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('previous_status', sa.String(length=16), nullable=True),
    sa.Column('previous_group_ids', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('restore_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', app.db.compiles_types.SqliteCompatibleBigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_connection_restrictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_restrictions'))
    )
    with op.batch_alter_table('connection_restrictions', schema=None) as batch_op:
        batch_op.create_index('ix_connection_restrictions_active', ['active'], unique=False)
        batch_op.create_index('ix_connection_restrictions_user_active', ['user_id', 'active'], unique=False)

    op.create_table('user_connection_limits',
    sa.Column('user_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=False),
    sa.Column('ip_limit', sa.Integer(), nullable=True),
    sa.Column('exempt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('id', app.db.compiles_types.SqliteCompatibleBigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_connection_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_connection_limits')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_connection_limits_user_id'))
    )
    op.create_table('user_connection_states',
    sa.Column('user_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('devices', sa.Integer(), nullable=False),
    sa.Column('address_sources', sa.Integer(), nullable=False),
    sa.Column('hwid_count', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('app_count', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.db.compiles_types.SqliteCompatibleBigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_connection_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_connection_states')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_connection_states_user_id'))
    )
    with op.batch_alter_table('user_connection_states', schema=None) as batch_op:
        batch_op.create_index('ix_user_connection_states_checked_at', ['checked_at'], unique=False)
        batch_op.create_index('ix_user_connection_states_verdict', ['verdict'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_limit', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('connection_limit')

    with op.batch_alter_table('user_connection_states', schema=None) as batch_op:
        batch_op.drop_index('ix_user_connection_states_verdict')
        batch_op.drop_index('ix_user_connection_states_checked_at')

    op.drop_table('user_connection_states')
    op.drop_table('user_connection_limits')
    with op.batch_alter_table('connection_restrictions', schema=None) as batch_op:
        batch_op.drop_index('ix_connection_restrictions_user_active')
        batch_op.drop_index('ix_connection_restrictions_active')

    op.drop_table('connection_restrictions')
    # ### end Alembic commands ###
