#!/usr/bin/env python3
import argparse
import hashlib
import json
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

LOCKFILE_NAMES = {
    "uv.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "bun.lock",
    "bun.lockb",
    "poetry.lock",
    "Pipfile.lock",
    "composer.lock",
    "Gemfile.lock",
    "Cargo.lock",
}
LOCALE_RE = re.compile(r"(^|/)locales/[^/]+\.json$")
WORKFLOW_RE = re.compile(r"^\.github/workflows/")
GENERATED_PATH_RE = re.compile(r"(^|/)service/api/")
GENERATED_HEADER_RE = re.compile(
    r"generated by orval|do not edit manually|auto-?generated|@generated", re.IGNORECASE
)
HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@\s*(.*)$")
LEDGER_TOKEN_RE = re.compile(r"^`?([A-Za-z0-9_./+-]+\.[A-Za-z0-9]+)`?$")
BACKTICK_RE = re.compile(r"`([^`]+)`")

SYMBOL_RULES = [
    (re.compile(r"\.py$"), re.compile(r"^\s*(?:async\s+def|def|class)\s+(\w+)")),
    (
        re.compile(r"\.[jt]sx?$"),
        re.compile(
            r"^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?"
            r"(?:function\s+(\w+)|class\s+(\w+)|(?:const|let|var)\s+(\w+)\s*[=:])"
        ),
    ),
    (re.compile(r"\.go$"), re.compile(r"^func\s+(?:\([^)]*\)\s*)?(\w+)")),
]

CATEGORY_ORDER = ["fork-only", "pure-addition", "override", "mechanical"]


def git(*args):
    result = subprocess.run(["git", *args], capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(f"error: git {' '.join(args)}\n{result.stderr.strip()}\n")
        raise SystemExit(2)
    return result.stdout


def resolve_ref(ref):
    return git("rev-parse", "--verify", ref).strip()


def is_mechanical_path(path):
    name = path.rsplit("/", 1)[-1]
    return (
        name in LOCKFILE_NAMES
        or bool(LOCALE_RE.search(path))
        or bool(WORKFLOW_RE.match(path))
        or bool(GENERATED_PATH_RE.search(path))
    )


def head_blob(ref, path):
    result = subprocess.run(
        ["git", "show", f"{ref}:{path}"], capture_output=True, text=True
    )
    return result.stdout if result.returncode == 0 else None


def looks_generated(ref, path):
    content = head_blob(ref, path)
    if content is None:
        return False
    head = "\n".join(content.splitlines()[:8])
    return bool(GENERATED_HEADER_RE.search(head))


def parse_name_status(base, head):
    out = git("diff", "--name-status", "-z", "-M", base, head)
    tokens = [t for t in out.split("\0") if t]
    entries = {}
    i = 0
    while i < len(tokens):
        status = tokens[i]
        code = status[0]
        if code == "R" or code == "C":
            entries[tokens[i + 2]] = "M"
            i += 3
        else:
            mapped = {"A": "A", "M": "M", "D": "D", "T": "M"}.get(code, "M")
            entries[tokens[i + 1]] = mapped
            i += 2
    return entries


def merge_ranges(lines):
    ranges = []
    for n in sorted(set(lines)):
        if ranges and n == ranges[-1][1] + 1:
            ranges[-1][1] = n
        else:
            ranges.append([n, n])
    return ranges


def scan_symbol(path, base_lines, lineno):
    for ext_re, sym_re in SYMBOL_RULES:
        if ext_re.search(path):
            for line in reversed(base_lines[: max(lineno - 1, 0)]):
                m = sym_re.match(line)
                if m:
                    return next(g for g in m.groups() if g)
            return None
    return None


def parse_file_diffs(base, head):
    out = git("diff", "--no-color", "--no-ext-diff", "-U3", base, head)
    files = {}
    current = None
    old_path = None
    in_hunk = False
    old_ln = new_ln = 0
    for line in out.splitlines():
        if line.startswith("diff --git "):
            current = None
            old_path = None
            in_hunk = False
            continue
        if not in_hunk and line.startswith("--- "):
            target = line[4:]
            old_path = None
            if target != "/dev/null":
                old_path = target[2:] if target.startswith("a/") else target
            continue
        if not in_hunk and line.startswith("+++ "):
            target = line[4:]
            if target == "/dev/null":
                path = old_path
            else:
                path = target[2:] if target.startswith("b/") else target
            if path is None:
                current = None
                continue
            current = {"added": [], "removed": []}
            files[path] = current
            continue
        if current is None:
            continue
        m = HUNK_RE.match(line)
        if m:
            in_hunk = True
            old_ln = int(m.group(1))
            new_ln = int(m.group(3))
            continue
        if line.startswith("-"):
            current["removed"].append(old_ln)
            old_ln += 1
        elif line.startswith("+"):
            text = line[1:].strip()
            if text:
                digest = hashlib.sha1(text.encode()).hexdigest()[:12]
                current["added"].append(digest)
            new_ln += 1
        elif line.startswith("\\"):
            continue
        else:
            old_ln += 1
            new_ln += 1
    return files


def attach_ranges_and_symbols(path, base, parsed):
    removed = parsed["removed"]
    ranges = merge_ranges(removed)
    has_rule = any(ext_re.search(path) for ext_re, _ in SYMBOL_RULES)
    if not ranges:
        return []
    if not has_rule:
        return [{"start": s, "end": e, "symbol": None} for s, e in ranges]
    content = head_blob(base, path)
    base_lines = content.splitlines() if content else []
    return [
        {"start": s, "end": e, "symbol": scan_symbol(path, base_lines, s)}
        for s, e in ranges
    ]


def classify(base, head):
    statuses = parse_name_status(base, head)
    parsed = parse_file_diffs(base, head)
    records = []
    for path, status in sorted(statuses.items()):
        diff = parsed.get(path, {"added": [], "removed": []})
        if is_mechanical_path(path):
            category = "mechanical"
        elif status == "A":
            category = "fork-only"
        elif status == "M" and looks_generated(head, path):
            category = "mechanical"
        elif diff["removed"]:
            category = "override"
        else:
            category = "pure-addition"
        record = {
            "path": path,
            "status": {"A": "added", "M": "modified", "D": "deleted"}[status],
            "category": category,
            "added_lines": 0,
            "removed_lines": len(diff["removed"]),
        }
        if category in ("pure-addition", "override"):
            record["added_lines"] = len(diff["added"])
            record["added_hashes"] = sorted(set(diff["added"]))
        if category == "override":
            record["override_ranges"] = attach_ranges_and_symbols(path, base, diff)
        records.append(record)
    return records


def build_report(base, head, records):
    summary = {c: 0 for c in CATEGORY_ORDER}
    override_lines = 0
    added_tracked = 0
    for r in records:
        summary[r["category"]] += 1
        if r["category"] == "override":
            override_lines += r["removed_lines"]
        if r["category"] in ("pure-addition", "override"):
            added_tracked += r["added_lines"]
    return {
        "version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "base": {"ref": base, "sha": resolve_ref(base)},
        "head": {"ref": head, "sha": resolve_ref(head)},
        "summary": {
            "total_files": len(records),
            **summary,
            "override_lines": override_lines,
            "fork_added_lines_in_tracked_files": added_tracked,
        },
        "files": [
            {k: v for k, v in r.items() if k != "added_hashes"} for r in records
        ],
        "files_with_hashes": records,
    }


def print_summary(report, top):
    s = report["summary"]
    print("Upstream Inventory")
    print(f"  base: {report['base']['ref']} ({report['base']['sha'][:12]})")
    print(f"  head: {report['head']['ref']} ({report['head']['sha'][:12]})")
    print()
    print(f"Files diverged: {s['total_files']}")
    for c in CATEGORY_ORDER:
        print(f"  {c:<14} {s[c]}")
    print()
    print(f"Override lines (upstream lines removed/changed): {s['override_lines']}")
    print(f"Fork lines added to upstream-tracked files: {s['fork_added_lines_in_tracked_files']}")
    overrides = [f for f in report["files"] if f["category"] == "override"]
    if overrides:
        print()
        print(f"Override files ({len(overrides)}):")
        for f in sorted(overrides, key=lambda x: -x["removed_lines"])[:top]:
            symbols = sorted({r["symbol"] for r in f.get("override_ranges", []) if r["symbol"]})
            sym = f"  [{', '.join(symbols[:3])}]" if symbols else ""
            print(f"  {f['removed_lines']:>5} lines  {f['path']}{sym}")
    mechanical = [f["path"] for f in report["files"] if f["category"] == "mechanical"]
    if mechanical:
        print()
        print(f"Mechanical files ({len(mechanical)}):")
        for p in mechanical:
            print(f"  {p}")


def load_ledger(path):
    try:
        text = Path(path).read_text()
    except OSError as exc:
        sys.stderr.write(f"error: cannot read ledger {path}: {exc}\n")
        raise SystemExit(2)
    entries = set()
    for line in text.splitlines():
        for m in BACKTICK_RE.finditer(line):
            token = LEDGER_TOKEN_RE.match(m.group(1))
            if token:
                entries.add(token.group(1))
    return entries


def ledger_check(report, ledger_path):
    ledger = load_ledger(ledger_path)
    overrides = {f["path"] for f in report["files"] if f["category"] == "override"}
    outside = sorted(overrides - ledger)
    stale = sorted(ledger - overrides)
    print()
    if outside:
        print(f"Ledger check FAILED: {len(outside)} override file(s) outside {ledger_path}:")
        for p in outside:
            print(f"  {p}")
    else:
        print(f"Ledger check OK: all {len(overrides)} override file(s) listed in {ledger_path}")
    if stale:
        print(f"Ledger note: {len(stale)} listed file(s) no longer override upstream:")
        for p in stale:
            print(f"  {p}")
    return bool(outside)


def baseline_check(report, baseline_path):
    try:
        previous = json.loads(Path(baseline_path).read_text())
    except (OSError, json.JSONDecodeError) as exc:
        sys.stderr.write(f"error: cannot read baseline {baseline_path}: {exc}\n")
        raise SystemExit(2)
    prev_files = previous.get("files_with_hashes") or previous.get("files") or []
    prev_map = {f["path"]: f for f in prev_files}
    violations = []
    for f in report["files_with_hashes"]:
        if f["category"] not in ("pure-addition", "override"):
            continue
        prev = prev_map.get(f["path"])
        if prev is None:
            violations.append(
                {"kind": "newly-diverged-file", "path": f["path"],
                 "new_lines": f["added_lines"]}
            )
            continue
        new_hashes = Counter(f.get("added_hashes", [])) - Counter(
            prev.get("added_hashes", [])
        )
        if new_hashes:
            violations.append(
                {"kind": "new-fork-code", "path": f["path"],
                 "new_lines": sum(new_hashes.values())}
            )
        if prev.get("category") == "pure-addition" and f["category"] == "override":
            violations.append({"kind": "escalated-to-override", "path": f["path"],
                               "new_lines": 0})
    print()
    if violations:
        print(f"Baseline check: {len(violations)} boundary violation(s) vs {baseline_path}:")
        for v in violations:
            extra = f" (+{v['new_lines']} lines)" if v["new_lines"] else ""
            print(f"  [{v['kind']}] {v['path']}{extra}")
    else:
        print(f"Baseline check OK: no new fork code in upstream-tracked files vs {baseline_path}")
    return violations


def main():
    parser = argparse.ArgumentParser(
        description="Inventory fork divergence from upstream and guard the override boundary."
    )
    parser.add_argument("--base", default="upstream/main", help="upstream ref (default: upstream/main)")
    parser.add_argument("--head", default="HEAD", help="fork ref (default: HEAD)")
    parser.add_argument("--json", action="store_true", help="print full JSON report to stdout")
    parser.add_argument("--json-file", metavar="PATH", help="write full JSON report to PATH")
    parser.add_argument(
        "--fail-on-override-outside-ledger",
        metavar="LEDGER",
        help="exit 1 if override files appear that are not listed in LEDGER",
    )
    parser.add_argument(
        "--baseline",
        metavar="REPORT",
        help="warn about new fork code in upstream files since a previous JSON report",
    )
    parser.add_argument("--top", type=int, default=15, help="number of top override files to show")
    args = parser.parse_args()

    resolve_ref(args.base)
    resolve_ref(args.head)
    records = classify(args.base, args.head)
    report = build_report(args.base, args.head, records)

    if args.json:
        json.dump(report, sys.stdout, indent=2)
        sys.stdout.write("\n")
    else:
        print_summary(report, args.top)

    if args.json_file:
        Path(args.json_file).write_text(json.dumps(report, indent=2) + "\n")

    failed = False
    if args.fail_on_override_outside_ledger:
        failed = ledger_check(report, args.fail_on_override_outside_ledger)
    if args.baseline:
        baseline_check(report, args.baseline)
    raise SystemExit(1 if failed else 0)


if __name__ == "__main__":
    main()
